version: '3.4'

services:
  airboxsystems.api:
    image: airboxsystems:dev
    container_name: AirboxSystems.API
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "AirboxSystems.API"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=
    volumes:
      - /Users/ricardocosta/dev/AirboxSystemsTest/AirboxSystemsTest/AirboxSystems.API:/app
      - /Users/ricardocosta/dev/AirboxSystemsTest/AirboxSystemsTest:/src
      - /Users/ricardocosta/vsdbg/vs2017u5:/remote_debugger:rw
      - /Users/ricardocosta/.nuget/packages/:/root/.nuget/packages:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/packages  \"/app/bin/Debug/net5.0/AirboxSystems.API.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true